# Generated by Django 5.1.15 on 2026-04-29 14:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuisineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'cuisine type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SearchArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('radius_meters', models.PositiveIntegerField()),
                ('query_text', models.CharField(blank=True, default='', max_length=500)),
                ('cuisine_filter', models.CharField(blank=True, default='', max_length=200)),
                ('last_fetched', models.DateTimeField(auto_now=True)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('city_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('admin_level_1', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'search area',
                'ordering': ['-last_fetched'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_place_id', models.CharField(blank=True, db_index=True, default='', help_text='Google Places API place_id. Empty if imported from CSV.', max_length=255, unique=True)),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='WGS84 lat/lng stored as PostGIS Geography POINT.', srid=4326)),
                ('address', models.TextField(blank=True, default='')),
                ('rating', models.FloatField(blank=True, null=True)),
                ('user_ratings_total', models.PositiveIntegerField(default=0)),
                ('price_level', models.IntegerField(blank=True, choices=[(0, 'Free'), (1, '$'), (2, '$$'), (3, '$$$'), (4, '$$$$')], null=True)),
                ('inferred_cuisine', models.CharField(blank=True, default='', help_text='Raw cuisine label from CSV import or Google types.', max_length=200)),
                ('fetched_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last data refresh (Smart Cache TTL reference).')),
                ('is_from_csv', models.BooleanField(default=False, help_text='True if imported from user CSV, not from Google API.')),
                ('cuisines', models.ManyToManyField(blank=True, related_name='restaurants', to='restaurants.cuisinetype')),
            ],
            options={
                'verbose_name': 'restaurant',
                'ordering': ['-user_ratings_total'],
                'indexes': [models.Index(fields=['rating'], name='restaurants_rating_677477_idx'), models.Index(fields=['price_level'], name='restaurants_price_l_0a568a_idx'), models.Index(fields=['inferred_cuisine'], name='restaurants_inferre_56d1a2_idx')],
            },
        ),
    ]
