# Generated by Django 5.1.15 on 2026-05-06 05:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_taskstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='fetched_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='google_place_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='inferred_cuisine',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='is_from_csv',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
