# Generated by Django 5.1.15 on 2026-04-29 14:55

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centroid', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Geometric centroid of the cluster.', srid=4326)),
                ('address', models.TextField(blank=True, default='', help_text='Reverse-geocoded address of the centroid.')),
                ('viability_score', models.FloatField(default=0, help_text='Market viability score (0-100).')),
                ('restaurant_count', models.PositiveIntegerField(default=0)),
                ('avg_rating', models.FloatField(blank=True, null=True)),
                ('avg_price_level', models.FloatField(blank=True, null=True)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('avg_nearby_competition', models.FloatField(default=0, help_text='Average number of competitors within epsilon radius.')),
                ('epsilon_used', models.FloatField(help_text='DBSCAN eps parameter in km.')),
                ('min_samples_used', models.PositiveIntegerField(help_text='DBSCAN min_samples parameter.')),
                ('cuisine_filter', models.CharField(blank=True, default='', max_length=200)),
                ('search_latitude', models.FloatField(blank=True, null=True)),
                ('search_longitude', models.FloatField(blank=True, null=True)),
                ('search_radius', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to=settings.AUTH_USER_MODEL)),
                ('restaurants', models.ManyToManyField(blank=True, related_name='clusters', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'cluster',
                'ordering': ['-viability_score'],
            },
        ),
    ]
