# Generated by Django 5.1.15 on 2026-04-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='polygon',
            field=models.JSONField(blank=True, help_text='GeoJSON representation of the cluster boundary.', null=True),
        ),
    ]
