# Generated by Django 5.1.15 on 2026-05-06 05:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0002_cluster_polygon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='avg_nearby_competition',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='epsilon_used',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='min_samples_used',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='polygon',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='viability_score',
            field=models.FloatField(default=0),
        ),
    ]
